### Create a user
POST http://localhost:3005/user HTTP/1.1
content-type: application/json

{
    "fullName": "Chaima Hoho",
    "email": "chaima@go.com",
    "passwod": "dododod"
}

### GET a user
GET http://localhost:3005/user/60af8c69a303c52920c9c3d6 HTTP/1.1
content-type: application/json

### GET all users
GET http://localhost:3005/user/all HTTP/1.1
content-type: application/json
###create a material
POST http://localhost:3005/material HTTP/1.1
content-type: application/json

{
"name":"c1",
"description":"cccc",
"category":"chaire"

}
### GET a material by id
GET http://localhost:3005/material/60b67b89218d4b2898eddc71 HTTP/1.1
content-type: application/json
### GET all users
GET http://localhost:3005/material/all HTTP/1.1
content-type: application/json